name: 'cur_anon'

config-version: 2
version: '0.1'

profile: 'cur_anon_duckdb'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  cur_validation:  # replace with your project name
    bronze:
      +materialized: view
    silver:
      +materialized: table

clean-targets:
    - "targets"
    - "dbt_packages"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]
