version: 2

sources:
  - name: input
    tables:
      - name: cur_raw
        description: "Local AWS CUR data in Parquet format, Hive-style partitioned"
        meta:
          external_location: "read_parquet('input/**/*.parquet', hive_partitioning = true, union_by_name = true)"
